<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251129163021 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE devices (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(50) NOT NULL, model VARCHAR(100) NOT NULL, external_id VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_11074E9A9F75D7B0 ON devices (external_id)');
        $this->addSql('CREATE INDEX IDX_11074E9AA76ED395 ON devices (user_id)');
        $this->addSql('CREATE TABLE measurements (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(50) NOT NULL, value DOUBLE PRECISION NOT NULL, unit VARCHAR(20) NOT NULL, measured_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, device_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_71920F21A76ED395 ON measurements (user_id)');
        $this->addSql('CREATE INDEX IDX_71920F2194A4C7D4 ON measurements (device_id)');
        $this->addSql('ALTER TABLE devices ADD CONSTRAINT FK_11074E9AA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE measurements ADD CONSTRAINT FK_71920F21A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE measurements ADD CONSTRAINT FK_71920F2194A4C7D4 FOREIGN KEY (device_id) REFERENCES devices (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE devices DROP CONSTRAINT FK_11074E9AA76ED395');
        $this->addSql('ALTER TABLE measurements DROP CONSTRAINT FK_71920F21A76ED395');
        $this->addSql('ALTER TABLE measurements DROP CONSTRAINT FK_71920F2194A4C7D4');
        $this->addSql('DROP TABLE devices');
        $this->addSql('DROP TABLE measurements');
    }
}
